### Import Libraries

In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt


### Read Dataset

In [2]:
dataset = pd.read_csv('~/Documents/interview/data/50_Startups.csv')

FileNotFoundError: [Errno 2] No such file or directory: '/Users/ssah/Documents/interview/data/50_Startups.csv'

In [ ]:
type(dataset)

In [ ]:
dataset.head()

In [ ]:
dataset.shape

In [ ]:
dataset.isna().sum()

In [ ]:
X=dataset.iloc[:,:-1].values
y=dataset.iloc[:,-1:].values

In [12]:
print(X)

[[165349.2 136897.8 471784.1 'New York']
 [162597.7 151377.59 443898.53 'California']
 [153441.51 101145.55 407934.54 'Florida']
 [144372.41 118671.85 383199.62 'New York']
 [142107.34 91391.77 366168.42 'Florida']
 [131876.9 99814.71 362861.36 'New York']
 [134615.46 147198.87 127716.82 'California']
 [130298.13 145530.06 323876.68 'Florida']
 [120542.52 148718.95 311613.29 'New York']
 [123334.88 108679.17 304981.62 'California']
 [101913.08 110594.11 229160.95 'Florida']
 [100671.96 91790.61 249744.55 'California']
 [93863.75 127320.38 249839.44 'Florida']
 [91992.39 135495.07 252664.93 'California']
 [119943.24 156547.42 256512.92 'Florida']
 [114523.61 122616.84 261776.23 'New York']
 [78013.11 121597.55 264346.06 'California']
 [94657.16 145077.58 282574.31 'New York']
 [91749.16 114175.79 294919.57 'Florida']
 [86419.7 153514.11 0.0 'New York']
 [76253.86 113867.3 298664.47 'California']
 [78389.47 153773.43 299737.29 'New York']
 [73994.56 122782.75 303319.26 'Florida']
 [67532

In [ ]:
print(y)

### One Hot Encoding

In [14]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(), [3])],remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [16]:
print(X)

[[0.0 0.0 1.0 165349.2 136897.8 471784.1]
 [1.0 0.0 0.0 162597.7 151377.59 443898.53]
 [0.0 1.0 0.0 153441.51 101145.55 407934.54]
 [0.0 0.0 1.0 144372.41 118671.85 383199.62]
 [0.0 1.0 0.0 142107.34 91391.77 366168.42]
 [0.0 0.0 1.0 131876.9 99814.71 362861.36]
 [1.0 0.0 0.0 134615.46 147198.87 127716.82]
 [0.0 1.0 0.0 130298.13 145530.06 323876.68]
 [0.0 0.0 1.0 120542.52 148718.95 311613.29]
 [1.0 0.0 0.0 123334.88 108679.17 304981.62]
 [0.0 1.0 0.0 101913.08 110594.11 229160.95]
 [1.0 0.0 0.0 100671.96 91790.61 249744.55]
 [0.0 1.0 0.0 93863.75 127320.38 249839.44]
 [1.0 0.0 0.0 91992.39 135495.07 252664.93]
 [0.0 1.0 0.0 119943.24 156547.42 256512.92]
 [0.0 0.0 1.0 114523.61 122616.84 261776.23]
 [1.0 0.0 0.0 78013.11 121597.55 264346.06]
 [0.0 0.0 1.0 94657.16 145077.58 282574.31]
 [0.0 1.0 0.0 91749.16 114175.79 294919.57]
 [0.0 0.0 1.0 86419.7 153514.11 0.0]
 [1.0 0.0 0.0 76253.86 113867.3 298664.47]
 [0.0 0.0 1.0 78389.47 153773.43 299737.29]
 [0.0 1.0 0.0 73994.56 122782.75 3

### Train Test Split

In [17]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y,train_size=0.8,random_state=0)

In [22]:
from sklearn.linear_model import LinearRegression

regressor = LinearRegression()
regressor.fit(X_train,y_train)

LinearRegression()

In [31]:
y_pred = regressor.predict(X_test)
print(np.concatenate((y_test,y_pred),axis=1))

[[103282.38       103015.20159795]
 [144259.4        132582.27760816]
 [146121.95       132447.73845175]
 [ 77798.83        71976.09851258]
 [191050.39       178537.48221057]
 [105008.31       116161.24230167]
 [ 81229.06        67851.69209676]
 [ 97483.56        98791.73374687]
 [110352.25       113969.43533014]
 [166187.94       167921.06569552]]


In [24]:
y_test

array([[103282.38],
       [144259.4 ],
       [146121.95],
       [ 77798.83],
       [191050.39],
       [105008.31],
       [ 81229.06],
       [ 97483.56],
       [110352.25],
       [166187.94]])

In [25]:
y_pred

array([[103015.20159795],
       [132582.27760816],
       [132447.73845175],
       [ 71976.09851258],
       [178537.48221057],
       [116161.24230167],
       [ 67851.69209676],
       [ 98791.73374687],
       [113969.43533014],
       [167921.06569552]])

In [27]:
print(regressor.coef_)
print(regressor.intercept_)

[[ 8.66383692e+01 -8.72645791e+02  7.86007422e+02  7.73467193e-01
   3.28845975e-02  3.66100259e-02]]
[42467.52924853]
