In [1]:
import numpy as np

In [7]:
temp = np.ones(20)

In [8]:
print(temp)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [9]:
arr_1d = np.array([1,2,3,4])

In [10]:
print(arr_1d)

[1 2 3 4]


In [11]:
type(arr_1d)

numpy.ndarray

In [12]:
arr_1d.ndim

1

In [13]:
arr_2d = np.array([[1,2,3,4],[5,6,7,8]])

In [14]:
arr_2d


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [15]:
print(arr_2d)

[[1 2 3 4]
 [5 6 7 8]]


In [16]:
type(arr_2d)

numpy.ndarray

In [17]:
arr_2d.ndim

2

In [19]:
arr_2d.size

8

In [20]:
arr_1d.size

4

In [21]:
arr_1d.dtype

dtype('int32')