In [2]:
import numpy as np

In [9]:
arr_1d = np.array([1,2,3,4])

In [10]:
print(arr_1d)

[1 2 3 4]


In [11]:
type(arr_1d)

numpy.ndarray

In [12]:
arr_1d.ndim

1

In [13]:
arr_2d = np.array([[1,2,3,4],[5,6,7,8]])

In [14]:
arr_2d


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [15]:
print(arr_2d)

[[1 2 3 4]
 [5 6 7 8]]


In [16]:
type(arr_2d)

numpy.ndarray

In [17]:
arr_2d.ndim

2

In [19]:
arr_2d.size

8

In [20]:
arr_1d.size

4

In [21]:
arr_1d.dtype

dtype('int32')

In [23]:
temp = np.ones((3,4))

In [24]:
temp

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [3]:
temp1 = np.ones((3,4), dtype= int)

In [4]:
temp1

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [5]:
np.arange(1,13,2)

array([ 1,  3,  5,  7,  9, 11])

In [9]:
np.linspace(1,4,5)

array([1.  , 1.75, 2.5 , 3.25, 4.  ])

In [11]:
ar_1d = np.arange(1,13,2)

In [14]:
ar_1d.reshape(3,2)

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

In [16]:
arr1 = np.arange(1,10).reshape(3,3)
arr2 = np.arange(1,10).reshape(3,3)

In [18]:
arr1+arr2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [19]:
np.add(arr1, arr2)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [20]:
np.subtract(arr1, arr2)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [21]:
arr1 / arr2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [22]:
arr1 * arr2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [23]:
arr1 @ arr2

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [24]:
arr1.dot(arr2)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [28]:
arr1.max()

9

In [29]:
arr1.argmax()

8

In [30]:
arr1.max(axis = 0)

array([7, 8, 9])

In [31]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
arr1.max(axis = 1)

array([3, 6, 9])

In [33]:
np.sum(arr1)

45

In [34]:
np.sum(arr1, axis = 0)

array([12, 15, 18])

In [35]:
np.sum(arr1, axis = 1)

array([ 6, 15, 24])

In [36]:
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [37]:
np.std(arr1)

2.581988897471611

## Array Slicing